export const SET_SELECTED_FILE_DATA = 'SET_SELECTED_FILE_DATA';
export const SET_FOLDER_TREE_VIEW_JSON = 'SET_FOLDER_TREE_VIEW_JSON';
export const REMOVE_FILE = 'REMOVE_FILE';
export const UPDATE_FILE_DATA = 'UPDATE_FILE_DATA';
export const UPDATE_FILE_EDIT_STATUS = 'UPDATE_FILE_EDIT_STATUS';